rest/page-data.ts
rest/pages.ts
rest/utils.ts

see [⬜scrapbox-userscript-stdのError Objectを変える](https://scrapbox.io/takker/⬜scrapbox-userscript-stdのError_Objectを変える)

Enable to apply `Result<T, E>` to any types

---

deps/scrapbox.ts
rest/profile.ts

[⬜Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/⬜Scrapbox_REST_APIのwrapperを実装する)

:sparkles: Get user profile

---

rest/page-data.ts
rest/replaceLinks.ts
rest/utils.ts

see [🏃Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/🏃Scrapbox_REST_APIのwrapperを実装する)

/api/pages/:projectname/replace/links

---

browser/websocket/room.ts
browser/websocket/shortcuts.ts

close [⬜patch()のupdateでページのメタデータを使えるようにする](https://scrapbox.io/takker/⬜patch()のupdateでページのメタデータを使えるようにする)

:+1: Enable to use metadata of the page on `update()`

---

browser/websocket/makeChanges.ts
browser/websocket/pull.ts

close [⬜ページ書き込み時のリンク更新がcase insensitiveになってた](https://scrapbox.io/takker/⬜ページ書き込み時のリンク更新がcase_insensitiveになってた)

Preserve letters

---

browser/websocket/room.ts
browser/websocket/shortcuts.ts

close [⬜patch()で空配列を返されたらページを削除](https://scrapbox.io/takker/⬜patch()で空配列を返されたらページを削除)

:sparkles: Delete pages when the callback returns an empty array

---

title.test.ts
title.ts

close [⬜なるべくpercent encodingしないタイトルを作](https://scrapbox.io/takker/⬜なるべくpercent_encodingしないタイトルを作)

:sparkles: Enable to create readable titles for URL

---

browser/websocket/room.ts
browser/websocket/shortcuts.ts

close [⬜patch()を中止できるようにする](https://scrapbox.io/takker/⬜patch()を中止できるようにする)

:sparkles: Abort patch when the callback returns undefined

---

browser/dom/caret.ts

close [⬜内部構造の変更でcaret()が壊れたのを直](https://scrapbox.io/takker/⬜内部構造の変更でcaret()が壊れたのを直)

:bug: #text-inputのReactの内部構造の変更に追随した

---

browser/websocket/socket.ts

fix [✅websocketを使い回す (scrapbox-userscript-std)](https://scrapbox.io/takker/✅websocketを使い回す_(scrapbox-userscript-std))

:bug: socketの接続・遮断前にlistenerを登録しないといけなかった

---

deps/scrapbox.ts
rest/link.ts

[📝Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/📝Scrapbox_REST_APIのwrapperを実装する)

:sparkles: Implement wrappers of /api/pages/:projectname/search/titles

---

deps/scrapbox.ts
rest/mod.ts
rest/search.ts

[📝Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/📝Scrapbox_REST_APIのwrapperを実装する)

:sparkles: Implement wrappers of cross searches

---

rest/getTweetInfo.ts
rest/getWebPageTitle.ts
rest/page-data.ts
rest/project.ts
rest/replaceLinks.ts
rest/search.ts

`const text = await res.text()`を`const text = await res.json()`と書き間違えていた

:bug: s/res.json()/res.text()/g

---

browser/dom/cache.ts
browser/dom/mod.ts

close [⬜Cache操作支援函数を入れる](https://scrapbox.io/takker/⬜Cache操作支援函数を入れる)

:sparkles: Implemented functions operating cache storages

---

browser/dom/cursor.d.ts
browser/dom/cursor.ts
browser/dom/mod.ts
browser/dom/position.ts
browser/dom/selection.d.ts
browser/dom/selection.ts
browser/dom/stores.ts
deps/scrapbox.ts

close [⬜scrapbox-userscript-stdにcaretとselectionを直接操作する函数を入れる](https://scrapbox.io/takker/⬜scrapbox-userscript-stdにcaretとselectionを直接操作する函数を入れる)

:sparkles: caretとselectionを操作する内部クラスを無理やり引きずり出す

---

deps/scrapbox-rest.ts
deps/scrapbox.ts
deps/testing.ts
rest/project.ts

see [📝Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/📝Scrapbox_REST_APIのwrapperを実装する)

✨ Implement the wrapper for /api/projects

---

browser/dom/cursor.ts
browser/dom/mod.ts
browser/dom/selection.ts
browser/dom/stores.ts

close [⬜takeStore()からCursorとSelectionの両方を一度に吐き出す](https://scrapbox.io/takker/⬜takeStore()からCursorとSelectionの両方を一度に吐き出す)

✨ Get both Cursor and Selection at once 

---

deps/scrapbox-rest.ts
rest/getSnapshots.ts

see [📝Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/📝Scrapbox_REST_APIのwrapperを実装する)

:sparkles: Implement wrappers for /api/page-snapshots/

---

browser/dom/caret.ts
browser/dom/click.ts
browser/dom/edit.ts
browser/dom/isHeightViewable.ts
browser/dom/motion.ts
browser/dom/node.ts
browser/dom/press.ts
browser/dom/statusBar.ts
browser/websocket/_fetch.ts
browser/websocket/applyCommit.ts
browser/websocket/deletePage.ts
browser/websocket/diff.ts
browser/websocket/id.ts
browser/websocket/makeChanges.ts
browser/websocket/patch.ts
browser/websocket/pin.ts
browser/websocket/pull.ts
browser/websocket/socket.ts

close [✅arrow functionsに直す (scrapbox-userscript-std)](https://scrapbox.io/takker/✅arrow_functionsに直す_(scrapbox-userscript-std))

:recycle: Converted functions to arrow functions

---

browser/websocket/makeChanges.ts
browser/websocket/patch.ts
parseYoutube.ts

close [✅patch()のサムネイル更新漏れ](https://scrapbox.io/takker/✅patch()のサムネイル更新漏れ)

🐛 Youtubeのサムネイルをページカードのサムネイルにできていなかった

---

rest/error.ts
rest/getGyazoToken.ts
rest/getSnapshots.ts
rest/getTweetInfo.ts
rest/getWebPageTitle.ts
rest/link.ts
rest/page-data.ts
rest/pages.ts
rest/profile.ts
rest/project.ts
rest/replaceLinks.ts
rest/search.ts

close [⬜UnexpectedResponseErrorにRequestとResponseを持たせる](https://scrapbox.io/takker/⬜UnexpectedResponseErrorにRequestとResponseを持たせる)

:boom: Make UnexpectedResponseError have Request and Response

---

rest/__snapshots__/pages.test.ts.snap
rest/__snapshots__/project.test.ts.snap
rest/error.ts
rest/getGyazoToken.ts
rest/getSnapshots.ts
rest/getTweetInfo.ts
rest/getWebPageTitle.ts
rest/link.ts
rest/page-data.ts
rest/pages.test.ts
rest/pages.ts
rest/profile.ts
rest/project.test.ts
rest/project.ts
rest/replaceLinks.ts
rest/search.ts

see [⬜Requestの組み立てとResponseの解析を分離](https://scrapbox.io/takker/⬜Requestの組み立てとResponseの解析を分離)

 ✨ extract request builder and response analyzer in `getPage`/`listPages` and `getProject`/`listProjects`

---

browser/dom/mod.ts
browser/dom/open.ts
browser/dom/pushPageTransition.ts
title.test.ts

close [⬜リンク先へスクロールする機能をscrapbox-userscript-stdに入れ](https://scrapbox.io/takker/⬜リンク先へスクロールする機能をscrapbox-userscript-stdに入れ)

:sparkles: リンク先へスクロールする

---

rest/mod.ts
rest/table.ts

see [📝Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/📝Scrapbox_REST_APIのwrapperを実装する)

:sparkles: Get a table from REST API

---

browser/dom/mod.ts
browser/dom/takeInternalLines.ts

close [✅scrapbox.Page.linesと同等のデータをshallow copyして返す関数を作る](https://scrapbox.io/takker/✅scrapbox.Page.linesと同等のデータをshallow_copyして返す関数を作る)

:sparkles: Provide a shallow copy of `lines`

---

.github/workflows/ci.yml
.github/workflows/udd.yml
deps/hash.ts
rest/mod.ts
rest/uploadToGCS.ts

see [⬜scrapoxのfile upload機能をscrapbox-userscript-stdに実装する](https://scrapbox.io/takker/⬜scrapoxのfile_upload機能をscrapbox-userscript-stdに実装する)

:sparkles: Implement an wrapper of /api/gcs

---

browser/dom/node.ts

ref #118 
関数の実装を#118 のものに置き換えた

:recycle: 本文データをshallow copyして使う

---

.github/workflows/ci.yml
.github/workflows/udd.yml
browser/dom/__snapshots__/extractCodeFiles.test.ts.snap
parser/__snapshots__/youtube.test.ts.snap
rest/__snapshots__/pages.test.ts.snap
rest/getCodeBlock.ts
rest/mod.ts

see [📝Scrapbox REST APIのwrapperを実装する](https://scrapbox.io/takker/📝Scrapbox_REST_APIのwrapperを実装する)

✨ add a wrapper of /api/code/:project/:title/:filename

---

browser/websocket/makeChanges.ts
browser/websocket/pull.ts
deps/socket.ts

close [✅scrapbox-userscript-stdでExternal Linksを更新できるようにする](https://scrapbox.io/takker/✅scrapbox-userscript-stdでExternal_Linksを更新できるようにする)

:sparkles: Send project links to scrapbox.io when updating External links in the page

---

browser/websocket/makeChanges.ts

close [✅scrapboxへ行リンクを別のリンクとして報告してしまっている (scrapbox-userscript-std)](https://scrapbox.io/takker/✅scrapboxへ行リンクを別のリンクとして報告してしまっている_(scrapbox-userscript-std))

:bug: Didn't identify [A#xxxx...] as [A] wrongly

---

rest/getCodeBlock.ts

close [⬜api/code/:projectname/:pagetitle/:filenameが404 not foundを返すときに対応できていない](https://scrapbox.io/takker/⬜api%2Fcode%2F:projectname%2F:pagetitle%2F:filenameが404_not_foundを返すときに対応できていない)

:bug: Faild to proceed when code blocks are not found

---

browser/websocket/makeChanges.ts

see [✅scrapbox-userscript-stdでExternal Linksを更新できるようにする](https://scrapbox.io/takker/✅scrapbox-userscript-stdでExternal_Linksを更新できるようにする#64f5350f1280f00000d98a94)

:bug: Faild to update pages which include `[/:project]` or `[/:project/]`

---

browser/websocket/diffToChanges.test.ts
browser/websocket/makeChanges.ts

deno.unstableを消してtype checkが通るようにもした

fix: scrapbox-parserの破壊的変更に伴うエラー修正

---

browser/websocket/_fetch.ts
browser/websocket/diffToChanges.ts
browser/websocket/updateCodeBlock.ts
browser/websocket/updateCodeFile.ts
deps/socket.ts
deps/testing.ts

scrapbox-userscript-websocketの型定義変更に対応
cf. https://github.com/takker99/scrapbox-userscript-websocket/pull/7

build(deno-udd): Update Deno dependencies

---

browser/websocket/__snapshots__/findMetadata.test.ts.snap
browser/websocket/findMetadata.test.ts
browser/websocket/findMetadata.ts
browser/websocket/isSameArray.test.ts
browser/websocket/isSameArray.ts
browser/websocket/makeChanges.ts
browser/websocket/patch.ts
deps/scrapbox-rest.ts
deps/scrapbox.ts
deps/socket.ts

close [✅️infoboxの更新などを反映する (scrapbox-userscript-std)](https://scrapbox.io/takker/✅️infoboxの更新などを反映する_(scrapbox-userscript-std))
Before the commit, `icons`, `files`, `helpfeels` and `infoboxDefinition` were not pushed

feat(websocket): Push all page metadata

---

browser/dom/_internal.test.ts
browser/dom/_internal.ts
browser/dom/mod.ts
browser/dom/textInputEventListener.ts

close [scrapbox-userscript-stdにaddTextInputEventListenerを実装する](https://scrapbox.io/takker/scrapbox-userscript-stdにaddTextInputEventListenerを実装する)

feat(browser): Keep listeners registered to `#text-input`

---

browser/websocket/findMetadata.ts

close [⬜️タイトル付きyoutubeリンクはサムネイルにしない (scrapbox-userscript-std)](https://scrapbox.io/takker/⬜️タイトル付きyoutubeリンクはサムネイルにしない_(scrapbox-userscript-std))

feat(websocket): Prevent named links of youtube from being selected as the thumbnail

---

browser/dom/cache.ts

fix(browser): `Response.headers` is immutable

---

.github/workflows/ci.yml
.github/workflows/udd.yml
deno.jsonc

ci(@molt/cli): Wrong command name

---

browser/websocket/applyCommit.ts
browser/websocket/patch.ts
browser/websocket/updateCodeBlock.ts
browser/websocket/updateCodeFile.ts
rest/getCodeBlocks.test.ts
rest/getCodeBlocks.ts

instead of writing `type Line = Page["lines"][number]`

refactor: Use pre- defined `BaseLine`  type

---

browser/dom/edit.ts
browser/dom/node.ts
rest/parseHTTPError.ts
text.ts

fix(deno-udd): Deal with Breaking Changes in `@core/unknownutil`

---

websocket/findMetadata.ts

`location` is not available in Node.js environment

---

websocket/patch.ts

chore(websocket): Forgot to remove `PinChange`

---

api.ts
api/pages.ts
api/pages/project.ts
api/pages/project/replace.ts
api/pages/project/replace/links.ts
api/pages/project/search.ts
api/pages/project/search/query.ts
api/pages/project/title.ts
api/pages/project/title/icon.ts
api/pages/project/title/text.ts
api/projects.ts
api/projects/project.ts
api/users.ts
api/users/me.ts

This PR refactors the API exports to remove all namespace exports and use unique identifiers for each API method. Previously, API routes were structured to match the REST endpoint hierarchy, with each endpoint exported as a namespace (e.g., `pages.project.title.get()`). This allowed method chaining but caused several issues:
- Documentation for namespace exports was not properly rendered on jsr.io, sometimes resulting in 404 errors.
- The method chain style (e.g., `pages.project.title.get()`) was rarely used in practice.
- Tree-shaking was ineffective, leading to unnecessarily large bundle sizes.
**Changes in this PR:**
- All namespace exports are removed.
- Each endpoint now exports functions with unique, collision-free identifiers (e.g., `getPage`).
- Intermediate route files and …

refactor(api): remove namespace exports and use unique identifiers for API methods

---

api/pages/project/search/titles.ts

Fix: https://github.com/takker99/scrapbox-userscript-std/pull/238
This PR renames the link search API functions for clarity and consistency.
Renamed exports in api/pages/project/search/titles.ts:
- makeGetRequest -> makeGetLinksRequest
- get -> getLinks
- list -> getLinksStream
Rationale:
- Clarifies these functions operate on link (searched title) resources, aligning with existing naming (e.g. getLinks in rest/link.ts).
- Reduces ambiguity with other generic get/list functions.
BREAKING CHANGE:
Existing imports using { get, list, makeGetRequest } from api/pages/project/search/titles.ts must be updated to { getLinks, getLinksStream, makeGetLinksRequest }.
No other code references required updates (rest layer already uses its own getLinks implementation).
Please review and merge. Thanks!

feat(api): rename get/list functions to getLinks/getLinksStream

---

README.md
deno.jsonc
deno.lock
scripts/build_npm.ts

and replace `jsr:@cosense/std` with `npm:@cosense/std` in the npm package version.
This is available thanks to https://github.com/scrapbox-jp/types/pull/78

feat: Support for Node.js commonjs package
